### ISSUE TITLE
VIN check for charge

### ISSUE THREAD

**Issue by Darosnl** [ngardiner/TWCManager#169] opened 2020-11-02 14:20 UTC
Hello,

Is it possible to control who can charge?

So, check is connected VIN is on the whitelist. 

If on Whitelist = max charge
If no VIN is detected, available 0kw.
If other VIN is detected, available 0kw

I was this morning at an Tesla Charger, the lights where Green but not charging. In the app there was an message "No available power"

I don't need green power checks, only control who can charge and who can't.

**Comment by MikeBishop** [comment] 2020-11-02 14:45
Duplicate of #104; while that's something we could implement, it's not something we have currently implemented.  One impediment to this is that not all TWCs report the connected VIN; it was added in a later firmware, so we have to be able to tolerate TWCs that don't.

**Closed by MikeBishop** 2020-11-02 14:45 UTC
Labels: duplicate
